### ISSUE TITLE
Adjust bar's height / width.

### ISSUE THREAD

**Issue by lidgnulinux** [Fabric-Development/fabric#17]
Hello, is there a way to adjust bar's height (for horizontal bar) or bar's width (vertical bar) ?

I try to tinker using css (`width: value` / `height: value`) but get no luck. Thanks.

**Comment by its-darsh** [comment]
width can be modified by changing the size of the content, for example we have children that takes around 30 pixels and there is the entire parent (i.e window) has a margin of 4 pixels so the whole thing is 34 pixels width, so how to change children size; you can lookup in the css file for `min-width` or `min-height` properties and modify it or you see if the widget itself takes that much of width (i.e a label with long text), so to modify the width you see what _actually_ eats size (ignoring margins and paddings)

for the height, you can't change it simply because the height is tied to the _anchor_ of the window, in our case (i.e the vertical-bar example) the anchor is set to `top bottom right`, so to change the height you have to edit the window margins (you can notice it at the class `VerticalBar` initialization) or you can just remove these two anchors (`top bottom`) and the height will be controlled same as height (based on the size of the children)

it's worth noting that GTK does not support the CSS properties you've mentioned, we use GTK as our backend and toolkit
