### ISSUE TITLE
[Request] Windows Support

### ISSUE THREAD

**Issue by ElinLiu0** [Fabric-Development/fabric#57]
I've saw on wiki that only Arch Linux and SUSE are supported.Please add Windows and more,plz.
: )

**Comment by its-darsh** [comment]
According to my knowledge, Fabric _might_ work on Windows, not natively, but through a hack, which's to basically use WSL and run Fabric through it. if WSL implements a windowing system for X11 then you would be able to use the `X11Window` class (see examples [in our wiki](https://wiki.ffpy.org/guide/first-widget/)), same way with the `WaylandWindow` class if Wayland windowing is present instead of X11, Since I’m unsure about WSL’s current windowing capabilities, I'm leaving it up to you to experiment.

Alternatively, it may be possible to use a virtual X11 server to make it work, though I’m not very familiar with those.

Either ways, Fabric does not support Windows (yet). While I’m open to adding support, as a non-Windows user, I wouldn’t be able to contribute much to its implementation. If anyone is interested in taking this on, contributions are welcome!

**Comment by ElinLiu0** [comment]
Thank you,i found the alternative.Closed
